name: Master workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore CleanApiSample.Api.sln
    - name: Build
      run: dotnet build CleanApiSample.Api.sln --no-restore
    - name: Test
      run: dotnet test CleanApiSample.Api.sln --no-build --verbosity normal
      
  Build-image-on-remote-Ubuntu:
    needs: [build]
    name: Build image on remote Ubuntu

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: SmartSoft-ME
        password: ${{ secrets.CR_PAT }}

    - name: Build the sales Docker image
      run: |
        docker build . -f CleanApiSample.Api/Dockerfile --tag ghcr.io/smartsoft-me/clean-api-sample:latest
        #docker run ghcr.io/smartsoft-me/clean-api-sample:latest
        docker push ghcr.io/smartsoft-me/clean-api-sample:latest
