name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  Create-Docker-Image:
    name: Build image on remote Ubuntu
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: SmartSoft-ME
        password: ${{ secrets.CR_PAT }}

    - name: Build the sales Docker image
      run: |
        docker build . -f sales.Api/Dockerfile --tag ghcr.io/smartsoft-me/CleanApiSample:latest
        docker run ghcr.io/smartsoft-me/CleanApiSample:latest -d
        docker push ghcr.io/smartsoft-me/CleanApiSample:latest
